"""Static reference metadata exposed by the assessment API."""

from __future__ import annotations

from .models import OnboardingFieldDefinition, OnboardingSchemaResponse, SubmissionSource


def build_onboarding_schema() -> OnboardingSchemaResponse:
    fields = [
        OnboardingFieldDefinition(
            key="primary_user_age_years",
            label="Primary User Age",
            type="integer",
            unit="years",
            required=True,
            minimum=18,
            maximum=100,
            section="household_profile",
            description="Age of the primary user.",
            example=34,
        ),
        OnboardingFieldDefinition(
            key="num_children_under_18",
            label="Children Under 18",
            type="integer",
            unit="count",
            required=True,
            minimum=0,
            maximum=20,
            section="household_profile",
            description="Number of dependent children under age 18 in the household.",
            example=1,
        ),
        OnboardingFieldDefinition(
            key="annual_household_income_usd",
            label="Annual Household Income",
            type="number",
            unit="usd_per_year",
            required=True,
            minimum=0,
            section="income_and_debt",
            description="Total annual household income from all sources.",
            example=72000,
        ),
        OnboardingFieldDefinition(
            key="total_household_debt_usd",
            label="Total Household Debt",
            type="number",
            unit="usd",
            required=True,
            minimum=0,
            section="income_and_debt",
            description="Total current household debt balance across loans and revolving obligations.",
            example=18500,
        ),
        OnboardingFieldDefinition(
            key="monthly_consumer_debt_payments_usd",
            label="Monthly Consumer Debt Payments",
            type="number",
            unit="usd_per_month",
            required=True,
            minimum=0,
            section="income_and_debt",
            description="Monthly payments on consumer debts such as credit cards, auto loans, and personal loans.",
            example=650,
        ),
        OnboardingFieldDefinition(
            key="liquid_assets_usd",
            label="Liquid Assets",
            type="number",
            unit="usd",
            required=True,
            minimum=0,
            section="assets_and_buffers",
            description="Accessible cash-like savings such as checking and savings account balances.",
            example=9000,
        ),
        OnboardingFieldDefinition(
            key="credit_card_revolving_balance_usd",
            label="Credit Card Revolving Balance",
            type="number",
            unit="usd",
            required=True,
            minimum=0,
            section="income_and_debt",
            description="Current credit card balance carried from month to month.",
            example=3200,
        ),
        OnboardingFieldDefinition(
            key="monthly_grocery_spend_usd",
            label="Monthly Grocery Spend",
            type="number",
            unit="usd_per_month",
            required=True,
            minimum=0,
            section="spending",
            description="Average monthly household spending on groceries and food at home.",
            example=650,
        ),
        OnboardingFieldDefinition(
            key="monthly_dining_spend_usd",
            label="Monthly Dining Spend",
            type="number",
            unit="usd_per_month",
            required=True,
            minimum=0,
            section="spending",
            description="Average monthly spending on restaurants, takeout, and dining away from home.",
            example=280,
        ),
        OnboardingFieldDefinition(
            key="research_consent_accepted",
            label="Research Consent Accepted",
            type="boolean",
            required=True,
            section="research",
            description="Must be true to create an assessment in the research workflow.",
            example=True,
        ),
        OnboardingFieldDefinition(
            key="research_consent_version",
            label="Research Consent Version",
            type="string",
            required=True,
            section="research",
            description="Version identifier for the consent language shown to the user.",
            example="consent_v1",
        ),
        OnboardingFieldDefinition(
            key="flow_version",
            label="Onboarding Flow Version",
            type="string",
            required=True,
            section="research",
            description="Version identifier for the onboarding flow used to collect this response.",
            example="onboarding_v1",
        ),
    ]

    return OnboardingSchemaResponse(
        schema_version="assessment-input-v1",
        submission_source=SubmissionSource.onboarding,
        fields=fields,
    )

